name: Latest YouTube Videos
on:
  schedule:
    - cron: '0 0 */15 * *' #Runs every two weeks
  workflow_dispatch:

jobs:
  update-readme-with-medium:
    name: Update this repo's README with latest post from Medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM-POSS-LIST"
          feed_list: "https://medium.com/feed/@leo.bernal1946"
